{"ast":null,"code":"import _createClass from \"/Applications/XAMPP/xamppfiles/htdocs/fohle-interface/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createClass\";\nimport _classCallCheck from \"/Applications/XAMPP/xamppfiles/htdocs/fohle-interface/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/classCallCheck\";\nimport _assertThisInitialized from \"/Applications/XAMPP/xamppfiles/htdocs/fohle-interface/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/assertThisInitialized\";\nimport _inherits from \"/Applications/XAMPP/xamppfiles/htdocs/fohle-interface/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/inherits\";\nimport _createSuper from \"/Applications/XAMPP/xamppfiles/htdocs/fohle-interface/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createSuper\";\nimport _wrapNativeSuper from \"/Applications/XAMPP/xamppfiles/htdocs/fohle-interface/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/wrapNativeSuper\";\n/** An error emitted by Sentry SDKs and related utilities. */\nvar SentryError = /*#__PURE__*/function (_Error) {\n  _inherits(SentryError, _Error);\n  var _super = _createSuper(SentryError);\n  /** Display name of this error instance. */\n\n  function SentryError(message) {\n    var _this;\n    var logLevel = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 'warn';\n    _classCallCheck(this, SentryError);\n    _this = _super.call(this, message);\n    _this.message = message;\n    ;\n    _this.name = (this instanceof SentryError ? this.constructor : void 0).prototype.constructor.name;\n    // This sets the prototype to be `Error`, not `SentryError`. It's unclear why we do this, but commenting this line\n    // out causes various (seemingly totally unrelated) playwright tests consistently time out. FYI, this makes\n    // instances of `SentryError` fail `obj instanceof SentryError` checks.\n    Object.setPrototypeOf(_assertThisInitialized(_this), (this instanceof SentryError ? this.constructor : void 0).prototype);\n    _this.logLevel = logLevel;\n    return _this;\n  }\n  return _createClass(SentryError);\n}( /*#__PURE__*/_wrapNativeSuper(Error));\nexport { SentryError };","map":{"version":3,"sources":["../../src/error.ts"],"names":[],"mappings":";;;;;;AAEA;AAAA,IACA,WAAA;EAAA;EAAA;EACA;;EAKA,qBAAA,OAAA,EAAA;IAAA;IAAA,IAAA,QAAA,uEAAA,MAAA;IAAA;IACA,0BAAA,OAAA;IAAA,MAAA,OAAA,GAAA,OAAA;IAAA;IAEA,MAAA,IAAA,GAAA,0DAAA,SAAA,CAAA,WAAA,CAAA,IAAA;IACA;IACA;IACA;IACA,MAAA,CAAA,cAAA,gCAAA,0DAAA,SAAA,CAAA;IACA,MAAA,QAAA,GAAA,QAAA;IAAA;EACA;EAAA;AAAA,iCAfA,KAAA","sourcesContent":["import type { ConsoleLevel } from './logger';\n\n/** An error emitted by Sentry SDKs and related utilities. */\nexport class SentryError extends Error {\n  /** Display name of this error instance. */\n  public name: string;\n\n  public logLevel: ConsoleLevel;\n\n  public constructor(public message: string, logLevel: ConsoleLevel = 'warn') {\n    super(message);\n\n    this.name = new.target.prototype.constructor.name;\n    // This sets the prototype to be `Error`, not `SentryError`. It's unclear why we do this, but commenting this line\n    // out causes various (seemingly totally unrelated) playwright tests consistently time out. FYI, this makes\n    // instances of `SentryError` fail `obj instanceof SentryError` checks.\n    Object.setPrototypeOf(this, new.target.prototype);\n    this.logLevel = logLevel;\n  }\n}\n"]},"metadata":{},"sourceType":"module"}